name: Dependency flow

on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJSfeature
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      