version: "3.1"

services:
  db_dev:
    image: postgres:11
    hostname: db_dev
    restart: always
    ports:
      - 5434:5432
    env_file: .env
  db_test:
    image: postgres:11
    hostname: db_test
    restart: always
    ports:
      - 5435:5432
    env_file: .env.test
