name: CI Develop

on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - name: Up containers
        run: docker-compose up -d
      - name: Config database Test
        run: yarn db:reload:test
      - name: Run tests
        run: yarn test:cov
      - name: upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-test-report
          path: report
      - uses: actions/download-artifact