name: Docker Workflow

on: [push]

jobs: 
  run-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps: 
      - name: Log node node-version
        run: |
          node -v 
          cat /etc/os-release
          
