name: Matrix Workflow

on: [push]

jobs:
  api-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]
    steps: 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo ${{ matrix.node-version }}
      - run: ${{ matrix.os }}
