name: Create release test

on: 
  pull_request:
    branches: [develop]
    tags: 
      - 'v*.*.*'

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.head_commit.message }}
      - name: Create Branch Release
        id: 'create-release'
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes'
      - name: Merge Branch Release
        uses: Hatzelencio/merge-branch@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base: 'release-notes'