name: Create release test

on: 
  pull_request:
    branches: [develop]
    tags: 
      - 'v*.*.*'

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # for pull_request so we can do HEAD^2
          fetch-depth: 2

      - name: Get commit message
        id: get_commit_message
        run: |
          if   [[ '${{ github.event_name }}' == 'push' ]]; then
            echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)
          elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD^2)
          fi
      - name: Get release version
        id: release_version
        run: |
          echo ::set-output name=release_version::"${{ steps.get_commit_message.outputs.commit_message }} | cut -d'#' -f 2"
      - run: echo ${{ steps.release_version.outputs.release_version }}
