name: Create release teste

on: 
  pull_request:
    branches: [develop]

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch Release
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes'
      - name: Merge Branch Release
        uses: Hatzelencio/merge-branch@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base: 'release-notes'