name: Test API

on: [push]

jobs: 
  run-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:12-alpine
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      
          
