name: Test API

on: [push]

jobs: 
  run-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:12-alpine
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      
          
