name: Test API

on: [push]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Lint 
        run: yarn lint

  test-api:
    needs: [run-lint]
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Up containers
        run: docker-compose up -d
      - name: Config database Test
        run: yarn db:reload:test
      - name: Run tests
        run: yarn test


      
          
